#!/usr/bin/perl

use POSIX;
use warnings;
use strict;

#########################################################################
# Compress Logfile for saving disk usage.
# 	.. done by ATLAS.
#########################################################################

my $argc = @ARGV;
my $sys = "";
my $gap = "";
if ($argc == 2)
{
  ($sys, $gap ) = @ARGV;		# sys for Server, gap for today - gap
} else {
    print "wrong argument : usage : system gap \n";
    print "ex : logcomp CNMsvr 27 \n";
    exit;
} 

#########################################################################
# you must modify this.
#########################################################################
#$dir = "/logs/mes/log/";
my $today = `/usr01/snsadm/mes/cmd/dateprint $gap`;
chomp($today);

#$backupdir = $dir . $sys . "/log_backup/" ;
my $backupdir = "/logs/" . $sys . "/" ;

my $srcdir = "/logs/mes/log/" . $sys . "/" . $today;

#$log_file = "/logs/mes/log/" . $sys . "_LOG_BACKUP_" . $today . ".LOG";
my $log_file = $backupdir . $sys . "_LOG_BACKUP_" . $today . ".LOG";
open(STDOUT, "> $log_file");
open(STDERR, ">&STDOUT");


print "---------------- BATCH JOB START ----------------\n";
print "1. CronJob Start Time : ";
system("date");
print "2. Account Information : ";
system("whoami");
print "3. Target Date : $today \n";
print "4. Backup Dir : $backupdir \n";
#print "5. tar.gz filename to delete : $tar_backupdir \n";

# compress tar.gz file.
my $compress_backup_file = "/logs/mes/log/" . $sys . "/". $sys . "_" . $today . ".tar.gz";

if (access($compress_backup_file, &POSIX::R_OK))
{
   print "$compress_backup_file exists. quit\n";
   exit;
}

if ($sys eq "CNMsvr" or $sys eq "CNXsvr" or $sys eq "EDCsvr" or $sys eq "FMCsvr" or $sys eq "ILCsvr" or $sys eq "PEMsvr" or $sys eq "PEXsvr" or $sys eq "QRYsvr" or $sys eq "SCHsvr" or $sys eq "TEMsvr" or $sys eq "TEXsvr" or $sys eq "IFEsvr" or $sys eq "MATsvr" or $sys eq "CPTsvr")
{
   my $exe_run = "tar cvf - $srcdir | /usr/contrib/bin/gzip -9c > $compress_backup_file";
   my $output = system($exe_run);
   print "command($exe_run) return : $output \n";

   my $srcdir1 = "/logs/mes/log/" . $sys . "/*" . $today;
   $exe_run = "mv $srcdir1*tar.gz $backupdir";
   $output = system($exe_run);
   print "command(mv) return : $output \n";

   $exe_run = "rm -rf $srcdir";
   system($exe_run);

   #$delday = `/usr01/snsadm/mes/cmd/dateprint $dur`;
   #chomp($delday);
   #$tar_deldir = $dir . $sys . "/log_backup/". $sys . "_" . $delday.".tar.gz";
   #system("rm -f $tar_deldir");

   #print $tar_deldir ;
}
else
{
   #$delday = `/usr01/snsadm/mes/cmd/dateprint $dur`;
   #chomp($delday);
   #$tar_deldir = $dir . $sys . "/" . $delday;
   #system("rm -rf $tar_deldir");

   #print $tar_deldir ;
}
print "\n----------------- BATCH JOB END ------------------\n";
