#!/usr/bin/perl

#########################################################################
#
# indent "@(#) Simple JAVA Based Server Startup Script v1.0 11/10/23
#                                                  made by Aim Systems
#
#                                   All Rights reserved in 2004-2015
#
#########################################################################

#use strict;
use POSIX;
#use warnings;
use Time::Local;
use Time::HiRes qw(usleep);

my $exe_path = "";

#########################################################################
#
# ToDo : 
#       1) export MES_CFG="location of serverList.cfg's directory" 
#       2) export MES_CS_BIN="location of CS script and stop.sh"
#       3) modify $JAVA_ARG & $OSGI_PORT value according to yours.
# 
#########################################################################
my $CFG_LOC = getenv("MES_CFG");

if ($CFG_LOC eq "")
{
  print "Setup MES_CFG Environment Variable .profile or .cshrc\n";
  exit(1);
}

my $run_path = getenv("MES_CS_BIN");
if ($run_path eq "")
{
  print "set MES_CS_BIN Environment Variable in .profile or .cshrc\n";
  exit(1);
}


my $JAVA_ARG = "-DSeq=";       # for checking java processes
my $OSGI_PORT = "-Dprocess=";  # for stop osgi based java processes

my $p_name="";
my $p_pid="";
my $p_port="";
my $p_stime="";
my $p_tty="";
#########################################################################
# Process Status Format
#########################################################################
format STDOUT =
<*> @<<<<<<<<< : @<<<<<< - PORT: @<<<<<< - ST: @<<<<<<<<<<<<<<<<<<< - @<<<<<<<
$p_name, $p_pid, $p_port, $p_stime, $p_tty
.

#########################################################################
# Process Stop Format
########################################################################
format FMT_STOP =
<1> @<<<<<<<<< : @<<<<<< - PORT : @<<<<<< will be stopped.
$p_name, $p_pid, $p_port
.

my $p_group="";
my $p_count="";
#########################################################################
# Process Start Format
#########################################################################
format FMT_START = 
<1> Process Group : @<<<<<<<< - Name : @<<<<<<<<< - Cnt : 1, Run : @<
$p_group, $p_name, $p_count
.
  


#########################################################################

#########################################################################
# Basic Information 
#########################################################################
my $host_name = `hostname`;
chomp($host_name);
$host_name =~tr/a-z/A-Z/;
my $get_ip_cmd = "getip $host_name";   # HP-UX specific command 
my $my_ipaddress = `$get_ip_cmd`;
chomp($my_ipaddress);
my $id = `whoami`;
chomp($id);


#########################################################################
#
# Process to invoke !!
# [WARNING] You must setup the $MES_CFG/serverList.cfg file correctly.
#
#########################################################################

my $cnt = 0;
my $tmp = "";

my %proc_reg = ();     # named hash variables for non-java apps
my %proc_exist = ();   # to fork processes one after another -s 1,2,3...


#########################################################################
#
# for logging who used this script.
#
#########################################################################

my $log_path = getenv("HOME") . "/log/mesproc";
my $today = `date +%Y%m%d`;
my $today_proc = `date "+%Y%m%d%H%M%S"`;
chomp($today);
chomp($today_proc);
my $log_file = "MES_STARTUP" . $today . ".LOG";

my $log_file_path = $log_path .  "/" . $log_file;
open(logH, ">> $log_file_path");


#########################################################################
# sub routine : write_log
#########################################################################
sub write_log {
  my $time_stamp = "[" . `date "+%Y%m%d %H:%M:%S"`;
  chomp($time_stamp);
  $time_stamp .= "]";
  print logH $time_stamp . " " . $_[0] . "\n";
}

sub getTime( $$ ) {
    my $date = $_[0];
    my $diff = $_[1];
    my $year    = substr($date,0,4);
    my $mon     = substr($date,4,2);
    my $mday    = substr($date,6,2);
    my $hours   = substr($date,8,2);
    my $min     = substr($date,10,2);
    my $sec     = substr($date,12,2);
    return timelocal($sec, $min, $hours, $mday, $mon - 1, $year) - $diff;
}

sub getDiffer
{
    # day-hh:mm:ss format
    my $elapsed_time = 0;
    my $a1 = "";
    my $a2 = 0;
    my $days = 0;
    my $hrs = 0;
    my $min = 0;
    my $sec = 0;
    my $tmp = "";
    $_ = $_[0];
    ($a1, $a2) = split(/-/);
    if ($a2 == 0 )
    {
      # only time
      $tmp = $a1;
    } else {
      $days = $a1;
      $tmp = $a2;
    }

    my @alist;
    my $count;
    @alist = split(/:/, $tmp);
    $count = @alist;
    if ($count == 2)
    {
      $min = $alist[0]; 
      $sec = $alist[1];
    } else {
      $hrs = $alist[0];
      $min = $alist[1];
      $sec = $alist[2];
    }

    $elapsed_time = 24*60*60*$days + 60*60*$hrs + 60*$min + $sec;
    return ($elapsed_time);
}
sub getDate( $$ ) {
    my $date = $_[0];
    my $differ = $_[1];
    chomp($date);
    chomp($differ);
    my $elapsed_time = getDiffer($differ);
    my $time = &getTime( $date, $elapsed_time );
    (my $sec, my $min, my $hour, my $mday, my $mon, my $year, my $wday, my $yday, my $isdst) = localtime( $time );
    return sprintf("%04d/%02d/%02d<%02d:%02d:%02d>", $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
}


#########################################################################
# sub routine : format process 
#########################################################################
sub print_process {
  $p_name = $_[0];
  $p_pid = $_[1]; 
  $p_port = $_[2];
  $p_stime = $_[3];
  $p_tty = $_[4];
  write(STDOUT);
}


sub print_stop_process {
  open(FMT_STOP, ">&STDOUT");
  $p_name = $_[0];
  $p_pid = $_[1];
  $p_port = $_[2];
 
  write(FMT_STOP);
  close(FMT_STOP);
}
          
sub print_start_process {
  open(FMT_START, ">&STDOUT");
  $p_group = $_[0];
  $p_name = $_[1];
  $p_count = $_[2];
 
  write(FMT_START);
  close(FMT_START);
}


          

#########################################################################
# 
# Sorting functions
#
#########################################################################

## sort by proces_name

sub my_sort_by_procname {
  
  my $a_before = "";

  foreach $rlEntry (@{$proc_exist{$a}}) {
    $a_before = $rlEntry->[0];
  }
 
  my $a_after = "";
  
  foreach $rlEntry (@{$proc_exist{$b}}) {
    $a_after = $rlEntry->[0];
  }

  my $ret = $a_before cmp $a_after;

  return ($ret);
}

# sort by process group

sub my_sort_by_procgrp {
  my $a_before = "";
  my $a_after = "";
  my $ret = "";
  foreach $rlEntry (@{$proc_reg{$a}}) {
    $a_before = $rlEntry->[2];
  }

  foreach $rlEntry (@{$proc_reg{$b}}) {
    $a_after = $rlEntry->[2];
  }

  $ret = $a_before cmp $a_after;

  return ($ret);
}


#########################################################################
#
# sub routine : my_sort 
#
#########################################################################

sub my_sort {
  my $a_before = "";
  my $a_after = "";
  foreach $rlEntry (@{$proc_reg{$a}}) {
    $a_before = $rlEntry->[7];
  }

  foreach $rlEntry (@{$proc_reg{$b}}) {
    $a_after = $rlEntry->[7];
  }

  return -1 if ($a_before < $a_after);
  return 0 if ($a_before == $a_after);
  return 1 if ($a_before > $a_after);
}

sub my_reverse_sort {
  my $a_before = 0;
  my $a_after = 0;
  
  foreach $rlEntry (@{$proc_reg{$a}}) {
    $a_before = $rlEntry->[7];
  }

  
  foreach $rlEntry (@{$proc_reg{$b}}) {
    $a_after = $rlEntry->[7];
  }

  return 1 if ($a_before < $a_after);
  return 0 if ($a_before == $a_after);
  return -1 if ($a_before > $a_after);
}


sub get_process_info {
  my ($cmd) = $_[0];
  my $user = "";
  my $pid = "";
  my $ppid = "";
  my $tty = "";
  my $etime = "";
  my $args = "";
  my $elapsed_time = "";
  my ($idx) = 0;
  my ($count) = 0;

  foreach $a (`$cmd`)
  {
     chomp($a);
     #$len = length($a);
     @alist = split(/ /, $a);
     $srv_name = "";
     $osgi_port = 0;

     $idx = 0;
     foreach $one(@alist)
     {
       if (length($one) == 0)
       {
          next;
       }
       $idx = $idx + 1;
       if ($idx == 1)
       {
          $user = $one;
       } elsif ($idx == 2) {
          $pid = $one;
       } elsif ($idx == 3) {
          $ppid = $one;
       } elsif ($idx == 4) {
          $tty = $one;
       } elsif ($idx == 5) {
          $etime = $one;
       } else {
         $bright = index($one, $JAVA_ARG);
         if ($bright == 0)
         {
           ($a, $srv_name) = split(/=/, $one);
         }

         $bright = index($one, $OSGI_PORT);

         if ($bright == 0)
         {
           ($a, $osgi_port) = split(/=/, $one);
           $osgi_port = $osgi_port + 0;
         }
       }

     }
     if (($osgi_port > 0) && ($srv_name ne ""))
     {
        $idx = $idx + 1;
        $count = $count + 1;
        #print "   <$idx> $srv_name($pid) - port : $osgi_port : $stime  $tty\n";
        $srv_group = $srv_name;
        $srv_group =~ tr/0-9/ /;
        $srv_group =~ s/ //g;
        #$rlEntry = [$srv_name, $osgi_port, $tty];
        #push (@{$proc_exist{$srv_name}}, $rlEntry);

        $elapsed_time = getDate($today_proc, $etime);

        foreach $procname (sort my_sort_by_procgrp keys %proc_reg) {
          foreach $rlEntry (@{$proc_reg{$procname}}) {
            if ($rlEntry->[0] eq $srv_name)
            {
              $rlEntry->[8] = $pid;
              $rlEntry->[9] = $osgi_port;
              $rlEntry->[10] = $elapsed_time;
              $rlEntry->[11] = $tty;
            }
          }
        }
      }
  }
  return ($count);
}

#########################################################################
#
# sub routine : server_list 
#               this function read the config. file(serverList.cfg),
#               and fill up the name hash variables.
#
#########################################################################
sub server_list {
  my($ServerListFile);
  $ServerListFile = getenv("MES_CFG") . "/serverList.cfg";
  open(infoH, $ServerListFile);

  while (<infoH>) {
    ($prog, $num, $group ,$start, $path, $single, $auto, $seq) = split(/:/);
    $tmp = substr($prog, 0, 1); 

    if ($tmp ne "#")
    {
        # warning ! $run_num is not a member of file format. it's runtime information.
        #$run_num = 0;
        $pid = 0;
        $time = "";
        $rlEntry = [$prog, $num, $group ,$start, $path, $single, $auto, $seq, $pid, $osgi_port, $time, $tty];
        push (@{$proc_reg{$prog}}, $rlEntry);
    }
  }
  close (infoH);
}

#########################################################################
#
# sub routine : search_proc 
#
#########################################################################
sub search_proc {
  my ($count);
  $count = 0;
  my ($return);
  $return = -1;

  my($progname) = @_;

  foreach $rlEntry (@{$proc_reg{$progname}}) {
      return ($rlEntry->[1]);
  }


  foreach $prog_name (sort my_sort keys %proc_reg) {
     foreach $rlEntry (@{$proc_reg{$prog_name}}) {
        if ($rlEntry->[0] =~ /$progname/)
        {
	   return (0);
        }	   
      }	 
  }

  return ($return);

}


#########################################################################
#
#
# sub routine : fork_java
#               this function is for spawning java apps. 
#
#########################################################################
sub fork_java {
  my ($path);
  my ($start);
  my ($program);
 
  $program = $_[0];
  $start = $_[1];
  $path = $_[2];
   
  chdir($path);
  print "    - path : $path \n";
  print "    - cmd : $start \n";
#  $cmd_string = "$start > /dev/null 2>&1 &";
   $cmd_string = "$start &";
  write_log("Invoke Process based on JAVA : $start, on path : $path");
  system($cmd_string); 
  sleep(1);
}


##########################################################################
#
# sub routine : fork_exe
#               to invoke the process you name it
#
##########################################################################
sub fork_exe {
  my ($run_exe);
  my ($number);

  fork_java($_[0], $_[1], $_[2]);

  #$number = check_process($_[0]);
  #write_log("[CHECK Process : $_[0], Number : $number ]");
}


sub fork_by_name {
  my ($progname);
 
  $progname = $_[0];
  foreach $prog_name (sort my_sort keys %proc_reg) {
       foreach $rlEntry (@{$proc_reg{$prog_name}}) {
        if ($rlEntry->[0] eq $progname)
        {
           print_start_process($rlEntry->[2], $rlEntry->[0], 0);
           fork_exe($rlEntry->[0], $rlEntry->[3], $rlEntry->[4]);
        }
      }
  }
}

#########################################################################
#
#
#
#########################################################################
$id = `whoami`;
chomp($id);

## tty check
$mytty = `tty`;
chomp($mytty);

$sret = 0;
#########################################################################
#
# sub routine : check_java
#               to check java the process you search.
# History : This script was able to handle normal process and java,
#           but, handle only java now.
#
#########################################################################

sub check_java {
  return (1);    # assume all processes are java-based ones.
}

sub ltrim($)
{
        my $string = shift;
        $string =~ s/^\s+//;
        return $string;
}



#########################################################################
#
# sub routine : check_process
#  
#########################################################################
sub check_process {
  my ($count);
  $count = 0;

  #$return = check_java($_[0]);
  $return = 1;
  if ($return > 0)
  {
    $cmd = "ps -efx user,pid,ppid,tty,etime,args | grep $_[0] | grep $id";
    $count = get_process_info($cmd);
    return ($count);
  }
  
  return ($count);
}

#########################################################################
#
# sub routine : similar_start
#
#########################################################################

sub similar_start {
  my ($moncnt);
  $moncnt = 0;
  my ($count);
  $count = 0;
  $list_count = 1;

  my($progname) = @_;

  similar_process($progname, 1);

  print "------------------------------------------------------------------------------\n";
  print " Start similar process \n";
  print "------------------------------------------------------------------------------\n";

  foreach $prog_name (sort my_sort keys %proc_reg) {
     foreach $rlEntry (@{$proc_reg{$prog_name}}) {
        if ($rlEntry->[0] =~ /$progname/)
        {
		$moncnt = check_process($rlEntry->[0]);
		if ($rlEntry->[1] > $moncnt)
		{
                        print_start_process($rlEntry->[2], $rlEntry->[0], 0);
			#print "[$list_count] Process Name : $rlEntry->[0], " .
                        #      "Registered Cnt : $rlEntry->[1], Run Time : $moncnt\n";
			fork_exe($rlEntry->[0], $rlEntry->[3], $rlEntry->[4]);
		} else {
                        print_start_process($rlEntry->[2], $rlEntry->[0], 1);
			#print "[$list_count] Process Name : $rlEntry->[0], " .
                              #"Registered Cnt : $rlEntry->[1], Now : $moncnt ! Enough !!\n";
		}
        }	   
     }	 
  }
}

#########################################################################
#
# sub routine : kill_process
#
#########################################################################
sub kill_process {
  $count = 0;

  $cnt = check_java($_[0]);
  $cnt = 1;
   
  #check_process($_[0]);
  if ($cnt > 0)
  {
    foreach $procname (sort my_reverse_sort keys %proc_reg) {
          foreach $rlEntry (@{$proc_reg{$procname}}) {
            if ($rlEntry->[0] eq $_[0])
            {
              $count ++;
              print_stop_process($rlEntry->[0], $rlEntry->[8], $rlEntry->[9]);
              kill(TERM, $rlEntry->[8]);
              #$cmd = `$run_path/stop.sh $port`;
              #print "$cmd .. \n";
              sleep(1); 
            }
          }
    }
  } 

  if ($count == 0)
  {
    print "\t[x] $_[0] not in memory.\n";
  }
}

#########################################################################
#
# sub routine : similar_kill
#
#########################################################################

sub similar_kill {
  my ($moncnt);
  $moncnt = 0;
  my ($count);
  $count = 0;
  $list_count = 1;

  my($progname) = @_;

  print "------------------------------------------------------------------------------\n";
  print " . Stop similar processes $progname \n";
  print "------------------------------------------------------------------------------\n";

  similar_process($progname);

  print "------------------------------------------------------------------------------\n";
  print " . In case of no process id or osgi port, skip stopping processes.\n";
  print " . stopping orders will be reserve. \n";
  print "------------------------------------------------------------------------------\n";

  sleep(1);

  foreach $prog_name (sort my_reverse_sort keys %proc_reg) {
      foreach $rlEntry (@{$proc_reg{$prog_name}}) {
        if ($rlEntry->[0] =~ /$progname/)
        {
            if (($rlEntry->[8] > 0) && ($rlEntry->[9] > 0))
            {
               #print "     . $rlEntry->[0] ($rlEntry->[8]) - port : $rlEntry->[9] will be dead.\n";
               print_stop_process($rlEntry->[0], $rlEntry->[8], $rlEntry->[9]);
               kill(TERM, $rlEntry->[8]);
               #$cmd = `$run_path/stop.sh $rlEntry->[9]`;
               #print "$cmd ..\n";
               sleep(1);   
            }
        }   
     }	 
  }
}


#########################################################################
#
# sub routine : status_process
#
#########################################################################
sub status_process {
  $counts = 1;
  my ($process_name);
  $process_name = $_[0];
  print "------------------------------------------------------------------------------\n";
  print " . Registered Process Name : $process_name, Count : $_[1] \n";
  print "------------------------------------------------------------------------------\n";

  $sret = check_java($_[0]);
  $sret = 1;
  if ($sret > 0)
  {
    $cmd = "ps -efx user,pid,ppid,tty,etime,args | grep $_[0] | grep $id";
    get_process_info($cmd);

    foreach $procname (sort my_sort keys %proc_reg) {
      foreach $rlEntry (@{$proc_reg{$procname}}) {
        if ($process_name eq $rlEntry->[0])
        {
          if ($rlEntry->[8] > 0)
          {
            print_process($rlEntry->[0], $rlEntry->[8], $rlEntry->[9], $rlEntry->[10], $rlEntry->[11]);
          } else {
            print_process($rlEntry->[0], 0, 0, 0, "NIL");
          }
        }
      }
    }

    print "------------------------------------------------------------------------------\n";
    return;
  } 
}

#########################################################################
#
# sub routine : similar_process
#
#########################################################################
sub similar_process {
  $counts = 1;
  my ($process_name);
  my ($bprint);

  $process_name = $_[0];
  $bprint = $_[1];

  $xms = 0;

  $cmd = "ps -efx user,pid,ppid,tty,etime,args | grep $id | grep $process_name"; 
  $idx = 0;
  get_process_info($cmd);

  if ($bprint == 1)
  {
    return;
  }

  $binit = 0;
  $idx = 0;
  $idx_sub = 0;
  $tmp = "";
  foreach $procname (sort my_sort keys %proc_reg) {
    foreach $rlEntry (@{$proc_reg{$procname}}) {
      if ($rlEntry->[0] =~ /$process_name/)
      {
        $idx = $idx + 1;
        if ($tmp ne $rlEntry->[2])
        {
          print " [$idx] Registered Server Group : $rlEntry->[2]\n";
          $tmp = $rlEntry->[2];
          $binit = 1;
        } 

        if ($rlEntry->[8] > 0)
        {
              print_process($rlEntry->[0], $rlEntry->[8], $rlEntry->[9], $rlEntry->[10], $rlEntry->[11]);
        } else { 
              print_process($rlEntry->[0], 0, 0, 0, "NIL");        
        }
        $idx_sub = 0;
      } 
    }
    $procname = "";
  }

  
  #$ServerListFile = getenv("MES_CFG") . "/serverList.cfg";
  #$cmd = "checkgroup $ServerListFile $JAVA_ARG $process_name";
  #$output = `$cmd`;
  #print $output;
}

#########################################################################
#
# sub routine : start_all
#
#########################################################################
sub start_all {
  my ($moncnt);
  $moncnt = 0;
  my ($count);
  $count = 0;
  $list_count = 1;

  print "------------------------------------------------------------------------------\n";
  print " Start all process \n";
  print "------------------------------------------------------------------------------\n";

  foreach $procname (sort my_sort keys %proc_reg) {
    $moncnt = check_process($procname);
    foreach $rlEntry (@{$proc_reg{$procname}}) {
      if ($rlEntry->[1] > $moncnt)
      {
        print "[$list_count] Process Name : $procname, " .
          "Registered Cnt : $rlEntry->[1], Now : $moncnt !\n";
        fork_exe($rlEntry->[0], $rlEntry->[3], $rlEntry->[4]);
      } else {
        print "[$list_count] Process Name : $procname, " .
          "Registered Cnt : $rlEntry->[1], Now : $moncnt ! Enough !!\n";
        print "\t $0 won't invoke $procname.\n"; 
      }
      $list_count ++;
    }
    $procname = "";
  }

  print "------------------------------------------------------------------------------\n";
}

#########################################################################
#
# sub routine : stop_all
#
#########################################################################
sub stop_all {
  $list_count = 1;
  print "------------------------------------------------------------------------------\n";
  print " Stop all processes\n";
  print "------------------------------------------------------------------------------\n";

  status_all(1);


  foreach $prog_name (sort my_reverse_sort keys %proc_reg) {
      foreach $rlEntry (@{$proc_reg{$prog_name}}) {
        if (($rlEntry->[8] > 0) && ($rlEntry->[9] > 0))
        {
            #print "     . $rlEntry->[0] ($rlEntry->[8]) - port : $rlEntry->[9] will be dead.\n";
            print_stop_process($rlEntry->[0], $rlEntry->[8], $rlEntry->[9]);
            kill(TERM, $rlEntry->[8]);
            #$cmd = `$run_path/stop.sh $rlEntry->[9]`;
            #print "$cmd ..\n";
            sleep(1);
        }
     }
  }



  print "------------------------------------------------------------------------------\n";
}

#########################################################################
#
# sub routine : status_all
#       .. .... .. .... . Runtime . .... 
#       ....
#
#########################################################################
sub status_all {
  print "==============================================================================\n";
  print "===============  ALL MES Processes(Custom Servers) Status  ===================\n";
  print "==============================================================================\n";

  $mes_root = getenv("HOME");
  if ($mes_root eq "")
  {
     print "[Error] not set MES_ROOT environment variable.\n";
     exit;
  }

  $counts = 1;
  $bprint = $_[0];

  $cmd = "ps -efx user,pid,ppid,tty,etime,args | grep java | grep $id";
 
  get_process_info($cmd);
  $binit = 0;
  $idx = 0;
  $idx_sub = 0;
  $tmp = "";

  if ($bprint == 1) 
  { return; }

  foreach $procname (sort my_sort keys %proc_reg) {
    foreach $rlEntry (@{$proc_reg{$procname}}) {
      if ($tmp ne $rlEntry->[2])
      {
        $idx = $idx + 1;
        print "------------------------------------------------------------------------------\n";
        print " [$idx] Registered Server Group : $rlEntry->[2]\n";
        print "------------------------------------------------------------------------------\n";
        $tmp = $rlEntry->[2];
        $binit = 1;

      }

      if ($rlEntry->[8] >= 0)
      {
          print_process($rlEntry->[0], $rlEntry->[8], $rlEntry->[9], $rlEntry->[10], $rlEntry->[11]);
      } else {
          print_process($rlEntry->[0], 0, 0, 0, "NIL");
      }
      $idx_sub = 0;
    }
  }

}

#############################################################################
#
# sub routine : greeting
#               .. .......
#
#############################################################################

sub greetings {
print "------------------------------------------------------------------------------\n";
print " M E S  P R O C E S S E S  M A N A G E M E N T  S C R I P T.\n";
print "------------------------------------------------------------------------------\n";
}

#############################################################################
#
# BODY - MAIN PROCEDURE
#
#############################################################################

$cmd = "";
$s_proc_name = "";
$numb = 0;

$argc = @ARGV;

$tmp = $0;
$tmp =~ s/\.//;

if ($argc == 1)
{
  ($cmd) = @ARGV;
} elsif ($argc == 2) {
  ($cmd, $s_proc_name) = @ARGV;
} elsif ($argc >= 3) {
  ($cmd, $s_proc_name, $numb) = @ARGV;
}


$cmd =~ tr/A-Z/a-z/;	# start, Start, START ... .. .... ..

$comments = "[CS Command Start]";
write_log($comments);

unlink(".tmpnc");
system("who  > .tmpnc");

open(infoH, ".tmpnc");
while (<infoH>) {
  ($login, $term, $Mon, $Day, $Time, $data) = split;
  $term = "/dev/" . $term;
  if ($term eq $mytty)
  {
    $comments = "[IP using CS script : " . $data . "]";
    write_log($comments);
  }
}

close(infoH);
if ($cmd eq "patch") {
  $comments = "[COMMAND : PATCH $s_proc_name ]";
  write_log($comments);
  server_list("master");
  patch_process($s_proc_name);
} elsif ($cmd eq "start") {
  server_list("master");
  greetings();
  unless($argc > 1) { die "(x)Error : $tmp start must be with {all | Process Name} argument.\n"; }
  
  if ($s_proc_name eq "all")
  {
    $comments = "[COMMAND : START ALL PROCESS]";
    write_log($comments);
    start_all();
  } else {
    print "Default invoke .. check configuration..\n";    
    $srch_cnt = search_proc($s_proc_name);
    if ($srch_cnt == -1)
    {
	print "(x)Error : not Registered Process Name($s_proc_name). \n";
    } elsif ($srch_cnt == 0) {
        similar_start($s_proc_name);
    } else {
      $cnt = check_process($s_proc_name);
      if ($cnt >= $srch_cnt)
      {
        print "Sufficient process. Not invoke process.\n";
        $comments = "[$s_proc_name Sufficient process. Not Invoke Process.]";
      } else {
        $comments = "[$s_proc_name Insufficient process. Invoke x $srch_cnt - $cnt."; 
        fork_by_name($s_proc_name);
      }
    }	
  }
} elsif ($cmd eq "stop") {
  server_list("master");
  greetings();
  unless($argc > 1) { die "stop must be with {all | Process Name} argument.\n"; }

  if ($s_proc_name eq "all")
  {
    stop_all();
  } else {
    print "Default invoke .. check configuration..\n";    
    $srch_cnt = search_proc($s_proc_name);
    if ($srch_cnt == -1)
    {
	print "(x)Error : not Registered Process Name($s_proc_name). \n";
    } elsif ($srch_cnt == 0) {
        similar_kill($s_proc_name);
    } else {
      $cnt = check_process($s_proc_name);
      if ($cnt >= $srch_cnt)
      {
        kill_process($s_proc_name);
      }
    }	
  }
} elsif ($cmd eq "status") {
  server_list("master");
  greetings();
  unless($argc > 1) { die "status must be with {all | Process Name} argument.\n"; }
  
  if ($s_proc_name eq "all")
  {
    $comments =  "[COMMAND : STATUS ALL PROCESS]";
    write_log($comments);
    status_all();
  } else {
    $srch_cnt = search_proc($s_proc_name);
    if ($srch_cnt == -1) 
    {
      print "(x)Error : not Registered Process Name($s_proc_name). \n";
    } elsif ($srch_cnt == 0) {
      $comments =  "[COMMAND - similar : STATUS $s_proc_name]";
      similar_process($s_proc_name);
    } else {
      $comments =  "[COMMAND : STATUS $s_proc_name]";
      write_log($comments);
      status_process($s_proc_name, $srch_cnt);
    }	
  }

} elsif ($cmd eq "list") {
  server_list("master");
  greetings();

  print "------------------------------------------------------------------------------\n";
  print " . Registered Process Information\n";
  print "------------------------------------------------------------------------------\n";
  
  $list_count = 1;

  foreach $prog_name (sort my_sort keys %proc_reg) {
    foreach $rlEntry (@{$proc_reg{$prog_name}}) {
        print "[$list_count] Process Name : $prog_name, Registered Count : $rlEntry->[1]\n";
        print "\tRunString : $rlEntry->[3] \n";
        $list_count ++;
    }
  }  

} else {
  $tmp = $0;

  print "==============================================================================\n";
  print "============= TRULY  M E S  S T A R T   U P  S C R I P T  H E L P ============\n";
  print "==============================================================================\n";
  print "\t1. start all usage : $tmp start all \n";
  print "\t..... check all process, invoke process if insufficient.\n";
  print "\t2. start group usage : $tmp start group(eg.CNX)\n";
  print "\t..... check group(eg.CNX), invoke process if insufficient.\n";
  print "\t3. start server usage : $tmp start server(eg.CNXsrv11) \n";
  print "\t..... check server(eg.CNXsrv11), invoke process if insufficient.\n";
  
  print "\t4. stop all usage : $tmp stop all \n";
  print "\t..... stop all process. \n";
  print "\t5. stop group usage : $tmp stop group(eg.CNX)\n";
  print "\t..... stop group written down(all equivalent process.)\n";
  print "\t6. stop server usage : $tmp stop server(eg.CNXsrv11)\n";
  print "\t..... stop server written down(all equivalent process.)\n";
  
  print "\t7. status all usage : $tmp status all \n";
  print "\t..... status all process.\n";
  print "\t8. status group usage : $tmp status group(eg.CNX).\n";
  print "\t..... status group(all equivalent) \n";
  print "\t9. status server usage : $tmp status server(eg.CNXsrv11).\n";
  print "\t..... status server(all equivalent) \n";  
  
  print "\t10. list registered processes usage: $tmp list\n";
  print "\t..... show you all registered process and information.\n";
  # print "\t9. patch registered process usage: $tmp patch ServerName.\n";
  # print "\t..... terminate old version process. \n";
  # print "\t10. master usage: $tmp patch ServerName.\n";
  # print "\t..... make master server(invoke all the processes). \n";
  print "\t11. others - help.\n";
  print "\t..... shown this description you see.\n";
  print "\n";	
  print "\tSummary : $tmp { start|status|stop|help } { all|proc_name }.\n";
  print "\n\n -- Good Luck --\n";
  # help string
}

write_log("[MES Command END]");
close(logH);
unlink(".tmpnc");

